version: "3.7"
services:
    
    # This redis without auth is for local dev
    portfolio-redis:
        image: redis:latest
        ports:
            - 6379:6379
        container_name: portfolio-redis

    # This db is just for local development.
    portfolio-postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: portfolio
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
        volumes:
            - ./persistence/postgres:/var/lib/postgresql/data
        container_name: portfolio-postgres

    # The django API
    portfolio-backend:
        build: backend
        image: portfolio-backend:latest
        ports:
            - 8000:8000
        volumes:
            - ./backend:/backend
        depends_on:
            - portfolio-redis
            - portfolio-postgres
        container_name: portfolio-backend

    # Strapi instance for local dev
    portfolio-strapi:
        build: strapi
        image: portfolio-strapi:latest
        ports:
            - 1337:1337
        volumes:
            - ./strapi:/strapi
        depends_on:
            - portfolio-postgres
        container_name: portfolio-strapi

    portfolio-frontend:
        build: frontend
        image: portfolio-frontend:latest
        ports:
            - 3001:3000
        volumes:
            - ./frontend:/frontend
        environment:
            HOST: 0.0.0.0
        depends_on:
            - portfolio-backend
            - portfolio-strapi
        container_name: portfolio-frontend